<?php
if (file_exists('installed.lock')) {
    die('Application already installed.');
}

session_start();

// --- Action Handler ---
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {
    header('Content-Type: application/json');
    $action = $_POST['action'];

    if ($action === 'test_db') {
        $host = $_POST['db_host'];
        $name = $_POST['db_name'];
        $user = $_POST['db_user'];
        $pass = $_POST['db_pass'];

        try {
            $dsn = "mysql:host=$host;dbname=$name;charset=utf8mb4";
            $pdo = new PDO($dsn, $user, $pass, [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES   => false,
            ]);

            // Connection successful, now execute SQL
            $sql = file_get_contents('database.sql');
            $pdo->exec($sql);

            // Store credentials in session for the next step
            $_SESSION['db_credentials'] = [
                'host' => $host,
                'name' => $name,
                'user' => $user,
                'pass' => $pass,
            ];

            echo json_encode(['status' => 'success', 'message' => 'Database connection successful and schema imported.']);
        } catch (PDOException $e) {
            echo json_encode(['status' => 'error', 'message' => 'Database connection failed: ' . $e->getMessage()]);
        }
        exit();
    }

    if ($action === 'setup_admin') {
        if (!isset($_SESSION['db_credentials'])) {
            echo json_encode(['status' => 'error', 'message' => 'Database credentials not found. Please complete Step 2.']);
            exit();
        }

        $db = $_SESSION['db_credentials'];
        $name = htmlspecialchars($_POST['admin_name']);
        $email = $_POST['admin_email'];
        $phone = $_POST['admin_phone'];
        $password = $_POST['admin_password'];
        $pin = $_POST['admin_pin'];

        if (empty($name) || empty($email) || empty($phone) || empty($password) || empty($pin)) {
            echo json_encode(['status' => 'error', 'message' => 'All fields are required.']);
            exit();
        }

        if (!preg_match('/^[0-9]{4}$/', $pin)) {
            echo json_encode(['status' => 'error', 'message' => 'PIN must be a 4-digit number.']);
            exit();
        }

        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            echo json_encode(['status' => 'error', 'message' => 'Invalid email format.']);
            exit();
        }

        if (!preg_match('/^[0-9]{10,14}$/', $phone)) {
            echo json_encode(['status' => 'error', 'message' => 'Invalid phone number format.']);
            exit();
        }

        try {
            $dsn = "mysql:host={$db['host']};dbname={$db['name']};charset=utf8mb4";
            $pdo = new PDO($dsn, $db['user'], $db['pass']);

            $hashed_password = password_hash($password, PASSWORD_DEFAULT);
            $hashed_pin = password_hash($pin, PASSWORD_DEFAULT);

            $stmt = $pdo->prepare("INSERT INTO users (full_name, email, phone, password, pin, role) VALUES (?, ?, ?, ?, ?, 'admin')");
            $stmt->execute([$name, $email, $phone, $hashed_password, $hashed_pin]);

            // Define the config template as a string to avoid reading a non-existent file
            $config_template = <<<EOT
<?php
// includes/config.php - Database Configuration & App Settings

// --- Database Credentials ---
// Automatically generated by the installer. Do not edit.
define('DB_HOST', '{{DB_HOST}}');
define('DB_NAME', '{{DB_NAME}}');
define('DB_USER', '{{DB_USER}}');
define('DB_PASS', '{{DB_PASS}}');

// --- Application Settings ---
// This is set during installation and can be changed in the admin panel later
define('ADMIN_PHONE', '{{ADMIN_PHONE}}');

EOT;

            $config_content = str_replace(
                ['{{DB_HOST}}', '{{DB_NAME}}', '{{DB_USER}}', '{{DB_PASS}}', '{{ADMIN_PHONE}}'],
                [$db['host'], $db['name'], $db['user'], $db['pass'], $phone],
                $config_template
            );

            // Create the actual config file
            if (file_put_contents('includes/config.php', $config_content) === false) {
                 echo json_encode(['status' => 'error', 'message' => 'Failed to write config file. Please check file permissions for the includes/ directory.']);
                 exit();
            }

            file_put_contents('installed.lock', 'Installation completed on ' . date('Y-m-d H:i:s'));

            unlink(__FILE__);

            session_destroy();

            echo json_encode(['status' => 'success', 'message' => 'Admin account created successfully.']);
        } catch (PDOException $e) {
            echo json_encode(['status' => 'error', 'message' => 'Failed to create admin: ' . $e->getMessage()]);
        }
        exit();
    }
}

// --- Step 1: System Check ---
$php_version = phpversion();
$required_php_version = '8.0';
$php_version_ok = version_compare($php_version, $required_php_version, '>=');

$extensions = [
    'curl' => extension_loaded('curl'),
    'pdo_mysql' => extension_loaded('pdo_mysql'),
];
$extensions_ok = !in_array(false, $extensions);

$cache_dir = __DIR__ . '/cache';
if (!is_dir($cache_dir)) {
    @mkdir($cache_dir, 0755, true);
}
$is_writable = is_writable(__DIR__ . '/includes') && is_writable($cache_dir);

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Billpoint Installer</title>
    <style>
        body { font-family: Arial, sans-serif; background-color: #f4f4f4; }
        .container { max-width: 600px; margin: 50px auto; background: #fff; padding: 20px; border-radius: 5px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }
        .step { display: none; }
        .step.active { display: block; }
        h2 { color: #333; }
        .form-group { margin-bottom: 15px; }
        label { display: block; margin-bottom: 5px; }
        input[type="text"], input[type="password"], input[type="email"] { width: 100%; padding: 8px; border: 1px solid #ddd; border-radius: 3px; }
        .btn { background: #337ab7; color: #fff; padding: 10px 15px; border: none; border-radius: 3px; cursor: pointer; }
        .btn:hover { background: #286090; }
        .error { color: red; }
        .success { color: green; }
        #messages { margin-top: 15px; }
    </style>
</head>
<body>
    <div class="container">
        <h2>Billpoint Installation Wizard</h2>
        <div id="messages"></div>

        <!-- Step 1: System Check -->
        <div id="step1" class="step active">
            <h3>Step 1: System Requirements</h3>
            <p>PHP Version (<?php echo $required_php_version; ?>+):
                <?php if ($php_version_ok): ?>
                    <span class="success">OK (<?php echo $php_version; ?>)</span>
                <?php else: ?>
                    <span class="error">FAIL (<?php echo $php_version; ?>)</span>
                <?php endif; ?>
            </p>
            <p>cURL Extension:
                <?php if ($extensions['curl']): ?>
                    <span class="success">OK</span>
                <?php else: ?>
                    <span class="error">FAIL</span>
                <?php endif; ?>
            </p>
            <p>PDO MySQL Extension:
                <?php if ($extensions['pdo_mysql']): ?>
                    <span class="success">OK</span>
                <?php else: ?>
                    <span class="error">FAIL</span>
                <?php endif; ?>
            </p>
            <p>Writable Directories:
                <?php if ($is_writable): ?>
                    <span class="success">OK</span>
                <?php else: ?>
                    <span class="error">FAIL</span>
                <?php endif; ?>
            </p>
            <button class="btn" onclick="nextStep()" <?php if (!$php_version_ok || !$extensions_ok || !$is_writable) echo 'disabled'; ?>>Next</button>
        </div>

        <!-- Step 2: Database Setup -->
        <div id="step2" class="step">
            <h3>Step 2: Database Setup</h3>
            <form id="db-form">
                <input type="hidden" name="action" value="test_db">
                <div class="form-group">
                    <label for="db_host">Database Host</label>
                    <input type="text" id="db_host" name="db_host" required value="localhost">
                </div>
                <div class="form-group">
                    <label for="db_name">Database Name</label>
                    <input type="text" id="db_name" name="db_name" required>
                </div>
                <div class="form-group">
                    <label for="db_user">Database User</label>
                    <input type="text" id="db_user" name="db_user" required>
                </div>
                <div class="form-group">
                    <label for="db_pass">Database Password</label>
                    <input type="password" id="db_pass" name="db_pass">
                </div>
                <button type="submit" class="btn">Test & Install</button>
            </form>
        </div>

        <!-- Step 3: Admin Setup -->
        <div id="step3" class="step">
            <h3>Step 3: Admin Setup</h3>
            <form id="admin-form">
                <input type="hidden" name="action" value="setup_admin">
                <div class="form-group">
                    <label for="admin_name">Full Name</label>
                    <input type="text" id="admin_name" name="admin_name" required>
                </div>
                <div class="form-group">
                    <label for="admin_email">Email</label>
                    <input type="email" id="admin_email" name="admin_email" required>
                </div>
                <div class="form-group">
                    <label for="admin_phone">Phone Number</label>
                    <input type="text" id="admin_phone" name="admin_phone" required>
                </div>
                <div class="form-group">
                    <label for="admin_password">Password</label>
                    <input type="password" id="admin_password" name="admin_password" required>
                </div>
                <div class="form-group">
                    <label for="admin_pin">4-Digit PIN</label>
                    <input type="password" id="admin_pin" name="admin_pin" maxlength="4" required>
                </div>
                <button type="submit" class="btn">Create Admin & Finish</button>
            </form>
        </div>

        <!-- Step 4: Completion -->
        <div id="step4" class="step">
            <h3>Step 4: Installation Complete</h3>
            <p class="success">Congratulations! Billpoint has been installed.</p>
            <p><strong>Important:</strong></p>
            <ol>
                <li>For your security, <code>install.php</code> has been deleted.</li>
                <li>Set up your API keys in the Admin Panel.</li>
                <li>Configure your PHP Cron Jobs.</li>
            </ol>
            <a href="index.php" class="btn">Go to Homepage</a>
        </div>
    </div>

    <script>
        let currentStep = 1;
        const messagesDiv = document.getElementById('messages');

        function nextStep() {
            document.getElementById('step' + currentStep).classList.remove('active');
            currentStep++;
            document.getElementById('step' + currentStep).classList.add('active');
        }

        document.getElementById('db-form').addEventListener('submit', function(e) {
            e.preventDefault();
            const formData = new FormData(this);
            messagesDiv.innerHTML = '';

            fetch('install.php', {
                method: 'POST',
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                if (data.status === 'success') {
                    messagesDiv.innerHTML = `<p class="success">${data.message}</p>`;
                    nextStep();
                } else {
                    messagesDiv.innerHTML = `<p class="error">${data.message}</p>`;
                }
            })
            .catch(error => {
                messagesDiv.innerHTML = `<p class="error">An error occurred: ${error}</p>`;
            });
        });

        document.getElementById('admin-form').addEventListener('submit', function(e) {
            e.preventDefault();
            const formData = new FormData(this);
            messagesDiv.innerHTML = '';

            fetch('install.php', {
                method: 'POST',
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                if (data.status === 'success') {
                    messagesDiv.innerHTML = `<p class="success">${data.message}</p>`;
                    nextStep();
                } else {
                    messagesDiv.innerHTML = `<p class="error">${data.message}</p>`;
                }
            })
            .catch(error => {
                messagesDiv.innerHTML = `<p class="error">An error occurred: ${error}</p>`;
            });
        });
    </script>
</body>
</html>
